#!/usr/bin/env bash
# ===========================================================================
# plot_all.sh — Plotting-only pipeline for Anti-Collapse
# ===========================================================================
#
# Runs aggregation + plotting on existing experiment data without rerunning
# simulations. Designed to run on a Mac from saved results produced by
# anticollapse.sh on a DGX cluster.
#
# Usage:
#   ./plot_all.sh exp1            # Plot Experiment 1
#   ./plot_all.sh exp2            # Plot Experiment 2
#   ./plot_all.sh all             # Plot both experiments
#   ./plot_all.sh --help          # Show this help message
#
# Environment:
#   OUTDIR   — Root results directory  (default: results)
#   DPI      — Plot resolution         (default: 600)
#   SEEDS    — Comma-separated seeds   (default: 42,123,321)
#
# ===========================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTDIR="${OUTDIR:-results}"
DPI="${DPI:-600}"
SEEDS="${SEEDS:-42,123,321}"

usage() {
    cat <<'EOF'
plot_all.sh — Plotting-only pipeline for Anti-Collapse

Usage:
    ./plot_all.sh exp1            Plot Experiment 1
    ./plot_all.sh exp2            Plot Experiment 2
    ./plot_all.sh all             Plot both experiments
    ./plot_all.sh --help          Show this help message

Environment variables:
    OUTDIR   Root results directory  (default: results)
    DPI      Plot resolution         (default: 600)
    SEEDS    Comma-separated seeds   (default: 42,123,321)

Prerequisite:
    Experiment data must already exist under OUTDIR/exp1 and/or OUTDIR/exp2
    (generated by anticollapse.sh or smoke_test.sh).

What it does:
    1. Re-aggregates phase trajectories and learning curves across seeds
    2. Generates all plots (dynamics, envelopes, alpha, tau, phase summary)
    3. Generates summary tables

No simulation is run — this is safe to execute on a laptop/Mac.
EOF
    exit 0
}

plot_exp1() {
    echo "=== Plotting: Experiment 1 (Phase Dynamics) ==="
    echo "    Results: $OUTDIR/exp1 | DPI: $DPI | Seeds: $SEEDS"
    python "$SCRIPT_DIR/main_exp1.py" \
        --outdir "$OUTDIR/exp1" \
        --seeds "$SEEDS" \
        --models const,shared,diag,gru,lstm \
        --dpi "$DPI" \
        --plot_only
    echo "=== Experiment 1 plotting DONE ==="
}

plot_exp2() {
    echo "=== Plotting: Experiment 2 (Ablation Study) ==="
    echo "    Results: $OUTDIR/exp2 | DPI: $DPI | Seeds: $SEEDS"
    python "$SCRIPT_DIR/main_exp2.py" \
        --outdir "$OUTDIR/exp2" \
        --seeds "$SEEDS" \
        --models diag,gru,lstm \
        --dpi "$DPI" \
        --plot_only
    echo "=== Experiment 2 plotting DONE ==="
}

# Parse argument
case "${1:-}" in
    exp1)
        plot_exp1
        ;;
    exp2)
        plot_exp2
        ;;
    all)
        plot_exp1
        plot_exp2
        ;;
    --help|-h|help)
        usage
        ;;
    "")
        echo "Error: specify exp1, exp2, or all. Use --help for details." >&2
        exit 1
        ;;
    *)
        echo "Error: unknown argument '$1'. Use --help for details." >&2
        exit 1
        ;;
esac
